# Site settings
title: Home | H.J. Chen
description: 'AI & Edge Computing PhD candidate @ THU '
url: 'http://baytoro.github.io/'

baseurl: ''
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Hongjiang Chen'
  email: hjchen0725@hotmail.com

  github_username:  baytoro
  kaggle_username: baytoro
  zhihu_username: baytoro
#  weibo_username: 3263963512
#  weixingongzhonghao_username: test
  linkedin_username:  chenhongjiang

#  twitter_username: test
#  facebook_username: test
#  ins_username: test

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 6
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
